#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const crypto = require('crypto');

const repoRoot = path.resolve(__dirname, '..');
const outputPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(repoRoot, 'db', 'seed.sql');

function loadWindowScript(fileName) {
  const code = fs.readFileSync(path.join(repoRoot, fileName), 'utf8');
  const context = { window: {} };
  vm.createContext(context);
  vm.runInContext(code, context, { filename: fileName });
  return context.window;
}

function sql(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function json(value) {
  return sql(JSON.stringify(value || []));
}

function stableId(parts) {
  return crypto
    .createHash('sha1')
    .update(parts.filter(Boolean).join('|'))
    .digest('hex')
    .slice(0, 16);
}

function limitText(value, maxLength) {
  const text = String(value || '');
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength)}\n\n[긴 RSS 요약은 chunk 테이블에서 이어집니다.]`;
}

function chunks(value, size = 6000) {
  const text = String(value || '');
  const result = [];

  for (let index = 0; index < text.length; index += size) {
    result.push(text.slice(index, index + size));
  }

  return result;
}

function reportDateFromPath(filePath) {
  return path.basename(filePath).match(/^(\d{4}-\d{2}-\d{2})-/)?.[1] || null;
}

function reportTitle(body, date) {
  return body.match(/^#\s+(.+)$/m)?.[1] || `AI 밥그릇 데일리 리포트 - ${date}`;
}

const crawledWindow = loadWindowScript('crawled_data.js');
const trendsWindow = loadWindowScript('daily_trends.js');
const guidesWindow = loadWindowScript('daily_survival_guides.js');

const news = crawledWindow.crawledNews || [];
const summaries = crawledWindow.crawledSummaries || {};
const trendCards = trendsWindow.dailyTrendCards || [];
const survivalGuides = guidesWindow.dailySurvivalGuides || [];
const reportDir = path.join(repoRoot, 'reports', 'rss');
const archiveDir = path.join(repoRoot, 'data', 'daily-archives');
const reportFiles = fs.existsSync(reportDir)
  ? fs.readdirSync(reportDir)
    .filter((fileName) => /^\d{4}-\d{2}-\d{2}-ai-rss-report\.md$/.test(fileName))
    .sort()
  : [];
const archivedTrendCards = [];
const archivedSurvivalGuides = [];

function loadArchiveItems(suffix) {
  if (!fs.existsSync(archiveDir)) return [];

  return fs.readdirSync(archiveDir)
    .filter((fileName) => new RegExp(`^\\d{4}-\\d{2}-\\d{2}-${suffix}\\.json$`).test(fileName))
    .sort()
    .flatMap((fileName) => {
      const filePath = path.join(archiveDir, fileName);
      try {
        const items = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        return Array.isArray(items) ? items : [];
      } catch (error) {
        console.warn(`Skipping invalid archive ${fileName}: ${error.message}`);
        return [];
      }
    });
}

const archivedTrendIds = new Set();
loadArchiveItems('trends').forEach((card) => {
  if (!card?.id || archivedTrendIds.has(card.id)) return;
  archivedTrendIds.add(card.id);
  archivedTrendCards.push(card);
});

const archivedGuideIds = new Set();
loadArchiveItems('guides').forEach((guide) => {
  if (!guide?.id || archivedGuideIds.has(guide.id)) return;
  archivedGuideIds.add(guide.id);
  archivedSurvivalGuides.push(guide);
});

trendCards.forEach((card) => {
  if (!card?.id || archivedTrendIds.has(card.id)) return;
  archivedTrendIds.add(card.id);
  archivedTrendCards.push(card);
});

survivalGuides.forEach((guide) => {
  if (!guide?.id || archivedGuideIds.has(guide.id)) return;
  archivedGuideIds.add(guide.id);
  archivedSurvivalGuides.push(guide);
});

const lines = [
  '-- Auto-generated by scripts/export_cloudflare_d1_seed.js',
  'PRAGMA foreign_keys = ON;',
  'DELETE FROM crawled_news_summary_chunks;',
  'DELETE FROM crawled_news;',
  'DELETE FROM crawled_summaries;',
  'DELETE FROM trend_cards;',
  'DELETE FROM survival_guides;',
  'DELETE FROM daily_reports;'
];

news.forEach((item, index) => {
  const id = stableId([item.source, item.link, item.title]);
  const region = item.region === 'domestic' ? 'domestic' : 'overseas';
  const regionLabel = item.regionLabel || (region === 'domestic' ? '국내' : '해외');
  const fullSummary = item.fullSummary || item.summary || item.description || '';
  const rowSummary = limitText(fullSummary, 1800);
  lines.push(
    `INSERT OR REPLACE INTO crawled_news ` +
    `(id, source, title, korean_title, link, description, summary, full_summary, korean_summary, pub_date, ` +
    `region, region_label, categories_json, feed_categories_json, author, guid, comments, enclosure_json, feed_meta_json, sort_order) VALUES ` +
    `(${sql(id)}, ${sql(item.source)}, ${sql(item.title)}, ${sql(item.koreanTitle)}, ${sql(item.link)}, ${sql(rowSummary)}, ` +
    `${sql(rowSummary)}, ${sql(rowSummary)}, ${sql(limitText(item.koreanSummary, 1800))}, ${sql(item.pubDate)}, ` +
    `${sql(region)}, ${sql(regionLabel)}, ${json(item.categories)}, ${json(item.feedCategories)}, ${sql(item.author)}, ` +
    `${sql(item.guid)}, ${sql(item.comments)}, ${json(item.enclosure || {})}, ${json(item.feedMeta || {})}, ${index});`
  );

  chunks(fullSummary).forEach((chunk, chunkIndex) => {
    lines.push(
      `INSERT OR REPLACE INTO crawled_news_summary_chunks (news_id, chunk_index, content) VALUES ` +
      `(${sql(id)}, ${chunkIndex}, ${sql(chunk)});`
    );
  });
});

Object.entries(summaries).forEach(([region, value]) => {
  if (value && typeof value === 'object') {
    Object.entries(value).forEach(([period, content]) => {
      lines.push(
        `INSERT OR REPLACE INTO crawled_summaries (region, period, content) VALUES ` +
        `(${sql(region)}, ${sql(period)}, ${sql(content)});`
      );
    });
    return;
  }

  lines.push(
    `INSERT OR REPLACE INTO crawled_summaries (region, period, content) VALUES ` +
    `('overseas', ${sql(region)}, ${sql(value)});`
  );
});

archivedTrendCards.forEach((card, index) => {
  lines.push(
    `INSERT OR REPLACE INTO trend_cards ` +
    `(id, title, category, date, read_time, views, tags_json, summary, content, trends_json, ` +
    `why_matters_json, developer_actions_json, risks_json, source_links_json, sort_order, active) VALUES ` +
    `(${sql(card.id)}, ${sql(card.title)}, ${sql(card.category)}, ${sql(card.date)}, ${sql(card.readTime)}, ` +
    `${sql(card.views)}, ${json(card.tags)}, ${sql(card.summary)}, ${sql(card.content)}, ${json(card.trends)}, ` +
    `${json(card.whyMatters)}, ${json(card.developerActions)}, ${json(card.risks)}, ${json(card.sourceLinks)}, ${index}, 1);`
  );
});

archivedSurvivalGuides.forEach((guide, index) => {
  lines.push(
    `INSERT OR REPLACE INTO survival_guides ` +
    `(id, title, subtitle, date, read_time, category, author, image, introduction, sections_json, sort_order, active) VALUES ` +
    `(${sql(guide.id)}, ${sql(guide.title)}, ${sql(guide.subtitle)}, ${sql(guide.date)}, ${sql(guide.readTime)}, ` +
    `${sql(guide.category)}, ${sql(guide.author)}, ${sql(guide.image)}, ${sql(guide.introduction)}, ` +
    `${json(guide.sections)}, ${index}, 1);`
  );
});

reportFiles.forEach((fileName) => {
  const filePath = path.join(reportDir, fileName);
  const date = reportDateFromPath(filePath);
  if (!date) return;
  const body = fs.readFileSync(filePath, 'utf8');
  const relativePath = path.posix.join('reports', 'rss', fileName);
  lines.push(
    `INSERT OR REPLACE INTO daily_reports (date, title, body, path) VALUES ` +
    `(${sql(date)}, ${sql(reportTitle(body, date))}, ${sql(body)}, ${sql(relativePath)});`
  );
});

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, `${lines.join('\n')}\n`);

console.log(`Wrote ${outputPath}`);
console.log(`Seeded rows: news=${news.length}, summaries=${Object.keys(summaries).length}, trends=${archivedTrendCards.length}, guides=${archivedSurvivalGuides.length}, reports=${reportFiles.length}`);
